---
# This "main.yml" file is a playbook, because it starts with three dashes up top and because its top-level entries are "plays."

# Within the playbook, this "My one and only play" list item is a "play," which I can tell because:
# 1. It is a top-level list item in this file
# 2. It has a "hosts" property.
# 3. It has a "tasks" or "roles" property.
- name: "My one and only play"
  hosts: "all"
  tasks:
    - ansible.builtin.import_role:
        name: "../roles/helloworld"