# Autogenerated with an LLM from the PowerShell; 
# I'm sure this is mediocre Bash but ... shrug.

#!/usr/bin/env bash

set -e

script_root_parent="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ansible_code_directory="${script_root_parent}/ansible_demo_01"
ansible_configuration_file="${ansible_code_directory}/ansible.cfg"
write_results_here="${ansible_code_directory}/test-results/junit-results"
ansible_playbook_main_file="${ansible_code_directory}/playbooks/main.yml"

echo "Config file should be: '$ansible_configuration_file'"
echo "Results should write to: '$write_results_here'"

# Specify which Ansible configuration file to use
export ANSIBLE_CONFIG="$ansible_configuration_file"

# Manually configure JUnit output path since Ansible configuration file not working
mkdir -p "$write_results_here"
export JUNIT_OUTPUT_DIR="$write_results_here"

# Run Ansible
ansible-playbook "$ansible_playbook_main_file" -v